### ISSUE TITLE
Stand-alone and chrome differences

### ISSUE THREAD

**Issue by Henrietta1989** [Wyliodrin/WyliodrinSTUDIO#107]
Are there any documentation how stand-alone Wyliodrin STUDIO differs from Chrome app?

Can this stand-alone version run in Raspberry Pi 3 with Raspbian?

**Comment by ioanaculic** [comment]
There is not difference. We had to build the stand-alone app since Chome applications are not supported anymore.

You need to flash the SD card with the image you can download from the Wyliodrin application or you can use the standard Raspbian image and install [wyliodrin-app-server.](https://github.com/Wyliodrin/wyliodrin-app-server) by hand.
